### ISSUE TITLE
Version tag

### ISSUE THREAD

**Issue by wazum** [avionbg/save_close_ce#3]
Please tag a version on github and add it to packagist, so we can install the extension more easily. Thanks!

**Comment by EvilBMP** [comment]
@avionbg There are many people using composer to maintain their TYPO3 installations and tagged versions lead to a "cleaner" composer.json file. Also github automatically creates releases from tagged versions, which means archives are also created automatically by github. That would result in a simple download instead of a git clone using composer!

So why do you release new versions to TER, but don't provide tags within the git repository? That isn't that much work, is it?

Anyways, thanks for providing the extension :-)

**Comment by avionbg** [comment]
I've updated the version to 1.1.0 and tagged it so it should be now fine I guess.

**Comment by EvilBMP** [comment]
Now create an account at packagist.org and connect your github repository with packagist. Then the releases will be published at packagist.org automatically as well, after every commit/ push.

After that every developer could simply do a "composer require goran/save_close_ce". That would be perfect!

See: https://packagist.org/about#how-to-update-packages

**Comment by avionbg** [comment]
Done, packages are added manually even with linked account
https://packagist.org/packages/goran/save_close_ce

**Comment by EvilBMP** [comment]
Sorry for the late reply. As I know, automatic packeging is only available for "new" pushes. So let's see, if packagist will be updated after your upcomming commits. Nevertheless - thanks again :-)

**Comment by EvilBMP** [comment]
@avionbg Several commits and merges have been made since the last tag. Would you mind creating a new tag of the current master? Thx
